export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';
export const FETCH_PFOLIO_DATA_SUCCESS = 'FETCH_PFOLIO_DATA_SUCCESS';
export const FETCH_MENU_DATA_SUCCESS = 'FETCH_MENU_DATA_SUCCESS';
export const FETCH_MENU_DATA_FAIL = 'FETCH_MENU_DATA_FAIL';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const SCROLL_WORK_UP = 'SCROLL_WORK_UP';
export const SCROLL_WORK_DOWN = 'SCROLL_WORK_DOWN';
